### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by javiermortiz** [StevelandOH/dogwlkr#1]
Hi Stephen, here are some suggestions for your docs

MVP list
- [x] Routes, pet profiles, and activities should be full CRUD. Make sure your bullet points reflect that. A user can create, edit and delete routes, pet profiles and activities. Of course you decide how much you'd allow a user to update, depending on how difficult it is you might decide the user can only update the name and description of the route or maybe you'll allow the user to update the route itself.

DB Schema
- [x] Add the associations you plan to use or the schema image with the relationships (*, 1).
- [x] Pets need an ownerId to point them to the user who owns the dog.
- [x] Can an activity be owned by many dogs? if that is the case you do need the join table if an activity only belongs to one dog, just add the dogId and userId to the activities table. You don't need the dog name table as you have the dog info already available via the join table or the dogId if you decide to go that route.

**Comment by StevelandOH** [comment]
I got my db schema updated if you wanted to check it out, I'm thinking for the purposes of getting a solid base down and not worrying about having basic functionality, I'm going to set up the initial app to only have the ability for the user to have one pet registered...Im going to have the db setup to expand to more pets but wont be implimenting that with beta version....less things to map through and less immediate associations to make will allow my brain to free up time to dive into this google api docs more (i think i have it figured out) but yea, whatre your thoughts on this?
