### ISSUE TITLE
DB Schema Review

### ISSUE THREAD

**Issue by BCrawfordScott** [StevelandOH/dogwlkr#2]
Great work so far, a couple suggestions:

- [x] Change `petName` to `petId` in the activities table
- [x] Add `petId` to the routes table to associate with the pet as well
- [x] Your routes table looks like a good first pass, but I believe the googleMaps API is going to provide different/more information to you that you'll want to store.  Hold off finalizing the routes table and come back to it once you've spent some time with the googlemapsApi

**Comment by StevelandOH** [comment]
Thanks Brian!!  The way it's set up is the route belongs to the user not the pet, the activity does belong to the pet but because I am not needing to join any information from the pets table to activities table i was going to make the petName a varchar input - they will still be able to be ordered by petName on the GET /api/activities page.  Thoughts on that?

**Comment by StevelandOH** [comment]
As far as the routes go, I was thinking all the info that I'll need that I don't need to store (such as lat and lng) could hit an endpoint in the response then destructured to the table, will that not work?

**Comment by StevelandOH** [comment]
In this case the route isn't tracking the activity it's more along the lines of user to user these are the routes i like with a description, maybe tips from pet owner to pet owner about that specific route .... things like that, not necessarily the stats of that route and what the dog did on it.

So the app flow will be like okay I just did an activity, let me open the app and log it, if it was a cool walk (someplace new, a nice trail, something to stay away from perharps). you can then go to the routes and with your mouse make a path of the route with the google api leave all the info you want about that specific route and boom). almost like faved routes from activities.  The routes page can also be used to create a route to see what the distance and elevation will be before trekking it.

**Comment by StevelandOH** [comment]
Took care of the association with the Activities table, but let me know what you think about the routes, as I was saying those are associated to the user more than the pet.

**Comment by BCrawfordScott** [comment]
Hey Steve, that user story totally makes sense. I think that the google maps api is going to need you to store more data to hold onto the drawn route that you described, but you can work that out when you start working on the routes feature.  

Everything else looks good :+1:

**Comment by StevelandOH** [comment]
Great thanks Brian!
